CppCMS: I/O Stream manipulators
I/O Stream manipulators
Message Formatting (translation)
Functions
std::ios_base & booster::locale::as::posix (std::ios_base &ios)
std::ios_base & booster::locale::as::number (std::ios_base &ios)
std::ios_base & booster::locale::as::currency (std::ios_base &ios)
std::ios_base & booster::locale::as::percent (std::ios_base &ios)
std::ios_base & booster::locale::as::date (std::ios_base &ios)
std::ios_base & booster::locale::as::time (std::ios_base &ios)
std::ios_base & booster::locale::as::datetime (std::ios_base &ios)
std::ios_base & booster::locale::as::strftime (std::ios_base &ios)
std::ios_base & booster::locale::as::spellout (std::ios_base &ios)
std::ios_base & booster::locale::as::ordinal (std::ios_base &ios)
std::ios_base & booster::locale::as::currency_default (std::ios_base &ios)
std::ios_base & booster::locale::as::currency_iso (std::ios_base &ios)
std::ios_base & booster::locale::as::currency_national (std::ios_base &ios)
std::ios_base & booster::locale::as::time_default (std::ios_base &ios)
std::ios_base & booster::locale::as::time_short (std::ios_base &ios)
std::ios_base & booster::locale::as::time_medium (std::ios_base &ios)
std::ios_base & booster::locale::as::time_long (std::ios_base &ios)
std::ios_base & booster::locale::as::time_full (std::ios_base &ios)
std::ios_base & booster::locale::as::date_default (std::ios_base &ios)
std::ios_base & booster::locale::as::date_short (std::ios_base &ios)
std::ios_base & booster::locale::as::date_medium (std::ios_base &ios)
std::ios_base & booster::locale::as::date_long (std::ios_base &ios)
std::ios_base & booster::locale::as::date_full (std::ios_base &ios)
template<typename CharType >
details::add_ftime< CharType > booster::locale::as::ftime (std::basic_string< CharType > const &format)
template<typename CharType >
details::add_ftime< CharType > booster::locale::as::ftime (CharType const *format)
std::ios_base & booster::locale::as::gmt (std::ios_base &ios)
std::ios_base & booster::locale::as::local_time (std::ios_base &ios)
details::set_timezone booster::locale::as::time_zone (char const *id)
details::set_timezone booster::locale::as::time_zone (std::string const &id)
details::set_domain booster::locale::as::domain (std::string const &id)
Function Documentation
std::ios_base& booster::locale::as::currency (std::ios_base & ios) [inline]
Format currency, number is treated like amount of money
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::currency_default (std::ios_base & ios) [inline]
Set default currency formatting style -- national, like "$"
References booster::locale::ios_info::currency_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::currency_iso (std::ios_base & ios) [inline]
Set ISO currency formatting style, like "USD", (requires ICU >= 4.2)
References booster::locale::ios_info::currency_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::currency_national (std::ios_base & ios) [inline]
Set national currency formatting style, like "$"
References booster::locale::ios_info::currency_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date (std::ios_base & ios) [inline]
Format a date, number is treated as POSIX time
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date_default (std::ios_base & ios) [inline]
set default (medium) date formatting style
References booster::locale::ios_info::date_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date_full (std::ios_base & ios) [inline]
set full date formatting style
References booster::locale::ios_info::date_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date_long (std::ios_base & ios) [inline]
set long date formatting style
References booster::locale::ios_info::date_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date_medium (std::ios_base & ios) [inline]
set medium date formatting style
References booster::locale::ios_info::date_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::date_short (std::ios_base & ios) [inline]
set short date formatting style
References booster::locale::ios_info::date_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::datetime (std::ios_base & ios) [inline]
Format a date and time, number is treated as POSIX time
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
details::set_domain booster::locale::as::domain (std::string const & id) [inline]
Manipulator for switching message domain in ostream,
Note:
The returned object throws std::bad_cast if the I/O stream does not have message_format facet installed
Referenced by booster::locale::basic_message< char_type >::str().
template<typename CharType > details::add_ftime<CharType> booster::locale::as::ftime (std::basic_string< CharType > const & format)
Set strftime like formatting string
Please note, formatting flags are very similar but not exactly the same as flags for C function strftime. Differences: some flags as "%e" do not add blanks to fill text up to two spaces, not all flags supported.
Flags:
"%a" -- Abbreviated weekday (Sun.)
"%A" -- Full weekday (Sunday)
"%b" -- Abbreviated month (Jan.)
"%B" -- Full month (January)
"%c" -- Locale date-time format. **Note:** prefer using "as::datetime"
"%d" -- Day of Month [01,31]
"%e" -- Day of Month [1,31]
"%h" -- Same as "%b"
"%H" -- 24 clock hour [00,23]
"%I" -- 12 clock hour [01,12]
"%j" -- Day of year [1,366]
"%m" -- Month [01,12]
"%M" -- Minute [00,59]
"%n" -- New Line
"%p" -- AM/PM in locale representation
"%r" -- Time with AM/PM, same as "%I:%M:%S %p"
"%R" -- Same as "%H:%M"
"%S" -- Second [00,61]
"%t" -- Tab character
"%T" -- Same as "%H:%M:%S"
"%x" -- Local date representation. **Note:** prefer using "as::date"
"%X" -- Local time representation. **Note:** prefer using "as::time"
"%y" -- Year [00,99]
"%Y" -- 4 digits year. (2009)
"%Z" -- Time Zone
"%%" -- Percent symbol
template<typename CharType > details::add_ftime<CharType> booster::locale::as::ftime (CharType const * format)
See ftime(std::basic_string<CharType> const &format)
std::ios_base& booster::locale::as::gmt (std::ios_base & ios) [inline]
Set GMT time zone to stream
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_zone().
std::ios_base& booster::locale::as::local_time (std::ios_base & ios) [inline]
Set local time zone to stream
References booster::locale::ios_info::get(), booster::locale::time_zone::global(), and booster::locale::ios_info::time_zone().
std::ios_base& booster::locale::as::number (std::ios_base & ios) [inline]
Format a number. Note, unlike standard number formatting, integers would be treated like real numbers when std::fixed or std::scientific manipulators were applied
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::ordinal (std::ios_base & ios) [inline]
Write an order of the number like 4th.
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::percent (std::ios_base & ios) [inline]
Format percent, value 0.3 is treated as 30%.
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::posix (std::ios_base & ios) [inline]
Format values with "POSIX" or "C" locale. Note, if locale was created with additional non-classic locale then These numbers may be localized
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::spellout (std::ios_base & ios) [inline]
Spell the number, like "one hundred and ten"
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::strftime (std::ios_base & ios) [inline]
Create formatted date time, Please note, this manipulator only changes formatting mode, and not format itself, so you are probably looking for ftime manipulator
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::time (std::ios_base & ios) [inline]
Format a time, number is treated as POSIX time
References booster::locale::ios_info::display_flags(), and booster::locale::ios_info::get().
std::ios_base& booster::locale::as::time_default (std::ios_base & ios) [inline]
set default (medium) time formatting style
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_flags().
std::ios_base& booster::locale::as::time_full (std::ios_base & ios) [inline]
set full time formatting style
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_flags().
std::ios_base& booster::locale::as::time_long (std::ios_base & ios) [inline]
set long time formatting style
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_flags().
std::ios_base& booster::locale::as::time_medium (std::ios_base & ios) [inline]
set medium time formatting style
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_flags().
std::ios_base& booster::locale::as::time_short (std::ios_base & ios) [inline]
set short time formatting style
References booster::locale::ios_info::get(), and booster::locale::ios_info::time_flags().
details::set_timezone booster::locale::as::time_zone (char const * id) [inline]
Set time zone using id
details::set_timezone booster::locale::as::time_zone (std::string const & id) [inline]
Set time zone using id