CppCMS: cppcms Namespace Reference
cppcms Namespace Reference
This is the namespace where all CppCMS functionality is placed.
Namespaces
namespace b64url
this namespace provides functions useful for modified Base64 encoding for URL. This encoding does not insert newline characters, do not pad the text with = character and use "_" and "-" instead of "+" and "/" characters reserved by URL format for special purposes.
namespace crypto
This namespace holds basic cryptographic utilities useful for save interaction with user.
namespace encoding
this Namespace holds various function for dealing with encoding
namespace filters
This namespace various filters that can be used in templates for filtering data.
namespace http
This namespace represent classes that are directly connected to handing HTTP requests and responses.
namespace json
This namespace includes all JSON parsing and formatting related classes and functions.
namespace rpc
This namespace holds API for implementing various RPC APIs, like JsonRPC.
namespace sessions
this namespace keeps various session storage backends
namespace util
This namespace holds various useful helper functions for we developer.
namespace views
this namespace holds all classes used for rendering CppCMS views.
namespace widgets
This namespace includes all the widgets (i.e. parts of HTML forms) supported by cppcms.
namespace xss
Namespace that holds Anti-Cross Site Scripting Filter support.
Classes
class application
application class is the base class for all user created applications.
class applications_pool
Application pool is the central class that holds user created applications.
class base_content
This is a simple polymorphic class that every content for templates rendering should be derided from it. It does not carry much information with exception of RTTI that allows type-safe casting of user provided content instances to target content class that is used by specific template.
class base_view
This class is base class for all views (skins) rendered by CppCMS template engine.
class triggers_recorder
triggers_recorder is a class that allows you to record all triggers added in certain scope.
class cache_interface
This class is the major gateway of the application to CppCMS caching abilities. Any access too cache would be done via this class.
class copy_filter
Copy the output stream part - "tee" filter.
class cppcms_error
Exception thrown by CppCMS framework.
struct form_flags
This struct holds various flags to control the HTML generation.
class form_context
This class represents the context required to generate the widgets' HTML.
class base_form
This class is the base class for any form or form widget used in CppCMS.
class form
The form is a container used to collect other widgets and forms into a single unit.
class forwarder
Class responsble for automaticall forwarding of HTTP/CGI requests to other hosts over SCGI.
class mount_point
This class represents application's mount point or the rule on which specific application is selected to process the query.
struct archive_traits
Special traits class that describes how to serialize various objects that are not defived from serializable_base.
class archive_error
Error thrown in case of serialization error.
class archive
Class that represents a binary archive that can be stored in persistent storage or transfered.
class serializable_base
Base abstract class for object that can be serialized into std::string.
class serializable
Abstract class for serialization object.
struct serialization_traits
This is the traits class for serialization traits.
class service
This class represent the central event loop of the CppCMS applications.
class session_api
This class represents the most generic implementation of session storage device.
class session_api_factory
the factory object that generates custom implemented session_api objects
class request_forgery_error
This exception is thrown when CSRF attempt is suspected:
class session_interface
This class provides an access to an application for session management.
class session_pool
This class provides an access to session management backends an allow customization.
class string_key
This is a special object that may hold an std::string or alternatively reference to external (unowned) chunk of text.
class thread_pool
This class provides an access to the thread pool where all CppCMS synchronous applications are executed.
class urandom_device
High entropy random number generator.
class url_dispatcher
This class is used to glue between member function of application class and urls.
class url_mapper
class for mapping URLs - the opposite of dispatch
Functions
template<typename T >
std::auto_ptr
< applications_pool::factory > applications_factory ()
template<typename T , typename P1 >
std::auto_ptr
< applications_pool::factory > applications_factory (P1 p1)
template<typename T , typename P1 , typename P2 >
std::auto_ptr
< applications_pool::factory > applications_factory (P1 p1, P2 p2)
void CPPCMS_API forward_connection (booster::shared_ptr< http::context > cont, std::string const &ip, int port)
template<typename Archivable >
archive & operator& (archive &a, Archivable &object)
template<typename Archivable >
archive & operator<< (archive &a, Archivable const &object)
template<typename Archivable >
archive & operator>> (archive &a, Archivable &object)
std::ostream & operator<< (std::ostream &out, string_key const &s)
bool operator== (string_key const &l, char const *r)
bool operator== (char const *l, string_key const &r)
bool operator== (string_key const &l, std::string const &r)
bool operator== (std::string const &l, string_key const &r)
bool operator!= (string_key const &l, char const *r)
bool operator!= (char const *l, string_key const &r)
bool operator!= (string_key const &l, std::string const &r)
bool operator!= (std::string const &l, string_key const &r)
bool operator<= (string_key const &l, char const *r)
bool operator<= (char const *l, string_key const &r)
bool operator<= (string_key const &l, std::string const &r)
bool operator<= (std::string const &l, string_key const &r)
bool operator>= (string_key const &l, char const *r)
bool operator>= (char const *l, string_key const &r)
bool operator>= (string_key const &l, std::string const &r)
bool operator>= (std::string const &l, string_key const &r)
bool operator< (string_key const &l, char const *r)
bool operator< (char const *l, string_key const &r)
bool operator< (string_key const &l, std::string const &r)
bool operator< (std::string const &l, string_key const &r)
bool operator> (string_key const &l, char const *r)
bool operator> (char const *l, string_key const &r)
bool operator> (string_key const &l, std::string const &r)
bool operator> (std::string const &l, string_key const &r)
Detailed Description
This is the namespace where all CppCMS functionality is placed.
Function Documentation
template<typename T > std::auto_ptr<applications_pool::factory> cppcms::applications_factory ()
Create application factory for application of type T, such as T has a constructor T::T(cppcms::service &s);
template<typename T , typename P1 > std::auto_ptr<applications_pool::factory> cppcms::applications_factory (P1 p1)
Create application factory for application of type T, such as T has a constructor T::T(cppcms::service &s,P1);
template<typename T , typename P1 , typename P2 > std::auto_ptr<applications_pool::factory> cppcms::applications_factory (P1 p1, P2 p2)
Create application factory for application of type T, such as T has a constructor T::T(cppcms::service &s,P1,P2);
void CPPCMS_API cppcms::forward_connection (booster::shared_ptr< http::context > cont, std::string const & ip, int port)
Forward the connection handled by cont to other node at IP ip listenning to on port port over SCGI protocol.
The context must be released first by calling cppcms::application::release_context() and it should not be used after this function call.
Please note: forwarding would not work for POST requests with multipart/form-data Content type as they are stored and managed differently.
bool cppcms::operator!= (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator!= (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator!= (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator!= (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
template<typename Archivable > archive& cppcms::operator& (archive & a, Archivable & object)
Operator that performs load or store object operations on archive
References cppcms::archive_traits< Object >::load(), and cppcms::archive::mode().
bool cppcms::operator< (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator< (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator< (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator< (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
template<typename Archivable > archive& cppcms::operator<< (archive & a, Archivable const & object)
Operator that saves an object to the archive
References cppcms::archive_traits< Object >::save().
std::ostream& cppcms::operator<< (std::ostream & out, string_key const & s) [inline]
Write the string to the stream
References cppcms::string_key::data(), and cppcms::string_key::size().
bool cppcms::operator<= (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator<= (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator<= (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator<= (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator== (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator== (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator== (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator== (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator> (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator> (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator> (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator> (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator>= (string_key const & l, char const * r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator>= (char const * l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator>= (string_key const & l, std::string const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
bool cppcms::operator>= (std::string const & l, string_key const & r) [inline]
Compare two strings
References cppcms::string_key::unowned().
template<typename Archivable > archive& cppcms::operator>> (archive & a, Archivable & object)
Operator that loads an object from the archive
References cppcms::archive_traits< Object >::load().